server:
  port: 8080
  servlet:
    context-path: /moneyne

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneyNe?characterEncoding=utf8&useSSL=true
    username: root
    password: root
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

sa-token:
  # token ??????? cookie ???
  token-name: token
  # token ????????? ??30??-1 ??????
  timeout: 604800
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: -1
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: true
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: true
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: uuid
  # ????????
  is-log: true
  #jwt????
  jwt-secret-key: abcopy1234567890

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.mahjongcamp.moneynebackend
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-filter-multipart-apis: true